// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0UarFIFc7SnwZViQ4pjK3k8_Jx5WTRdU',
    appId: '1:600134991620:web:1912e705d941976b2c9a51',
    messagingSenderId: '600134991620',
    projectId: 'chat-system-d4a1e',
    authDomain: 'chat-system-d4a1e.firebaseapp.com',
    databaseURL: 'https://chat-system-d4a1e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-system-d4a1e.firebasestorage.app',
    measurementId: 'G-7XRB3BJJ5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsZdBb7KPwWOg3H17lRSrzFk9CPCEPhzc',
    appId: '1:600134991620:android:4b112819eea4f2572c9a51',
    messagingSenderId: '600134991620',
    projectId: 'chat-system-d4a1e',
    databaseURL: 'https://chat-system-d4a1e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-system-d4a1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXYfE9Xf1zRfWelAWf8nx-a-jEfgB-clM',
    appId: '1:600134991620:ios:9dbf66fd7ff15b252c9a51',
    messagingSenderId: '600134991620',
    projectId: 'chat-system-d4a1e',
    databaseURL: 'https://chat-system-d4a1e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-system-d4a1e.firebasestorage.app',
    iosClientId: '600134991620-m0oo1j9la7eg4hh4blqbv1dduinaf9gc.apps.googleusercontent.com',
    iosBundleId: 'com.chitchat.chitChat',
  );
}
